const phrases = [
  "The true hero comes reluctantly - The Banner Saga 3, Aleo",
  "It's easier to forgive and enemy than to forgive a friend",
  "chaos is order yet undeciphered",
  "The classic smart person mistake - that no one out there is smarter than you",
  "Sometimes we assume the worst, because me fear to hope - The Witcher Series",
  "Perderme me importa un cuerno porque no se a donde voy - Solitario",
  "En visperas de un suicidio encontre mi llamada - Solitario",
  "Crime cannot be tolerated. Criminals thrive on the indulgence of society’s understanding - Batman Begins 18:27",
  "A person who cannot sacrifice everyrhing cannot change anything",
  "Even good leaders make poor choices, the best take resposbility for them - Kratos",
  "Comedians are the truth tellers of our age",
  "If you are gonna tell the peopel the truth, make sure they laugh or they’ll kill you",
  "Never too late to learn a new trick, is it? - Sindri, God of War",
  "Delight in the face of suffering is an act of rebellion - AC Valhalla",
  "Anyone can become a god or a devil, all it takes if for people to believe it - Eren Kruger",
  "The paint we can replace, but the time invested is forever lost",
  "We are our own devil, and we make this world our hell",
  "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
  "I’ve kill so much, and i have yet to gain anything from it",
  "You sold me queer giraffes - The Gladiator",
  "He will bring them death, and they will love him for it - The Gladiator",
  "A rich man watched his home burn, but with hopeful eyes, as death stood at its door, he smiled, because is always better to live, even in misery",
  "The gladiator - 1:49:30",
  "Death smiles at us all. All a man can do is smile back - The gladiator",
  "Ignorance of what?",
  "Never have i felt so vile than standing victorious on a battlefield, the thrill of victory fades quickly. What lingers long after, is always ugly. - The King",
  "Lejos del peligro, cualquiera se cree valiente",
  "Judgment comes from experience and experience comes from poor judgment",
  "Think of no one but me, look at nothing but my eyes, feel nothing, but me",
  "You need no be a good man, only a good king.",
  "Whar color do you see when you think about yourself? - The Windshield Wiper",
  "Healthy dose of C4 - Midnight Fight Express",
  "“He who has a why to live for can bear almost any how.” ― Friedrich Nietzsche",
  "Fairness is not a soldier’s concern - Peaky Blinders",
  "The cub that once hunted ate off your nose, now a wolf, he hungers for the rest - The Northman",
  "Standing on the bear ground, my head bathed by the ",
  "He does whatever he’s told. That’s how he makes his life easier. - Neon Genesis Evangelion",
  "Morir como si merecieras vivir",
  "Battle not with monsters, lest ye become a monster, and if gaze into the abyss long enough, the abyzz gazes also into you",
  "Honestly in small things, is not a small thing - Clean Code",
  "Love is a batteflied - Valera, Berserk",
  "Give a man a mask, and he will show you his true self. ",
  "Por muy feliz que seas tu vida es muy tiste - Replik",
  "A blade of pain found shelter and became power! - Vagabond, #302",
  "Swing the sword, until the excess drops! - Vagabond",
  "I can bear any pain as long as it has meaning",
  "Inside Musashi, strength bends to kindness - Vagabond",
  "Consider yourself lightly, consider the world deeply - Miyamoto Musashi",
  "The best way to get what you want, is by deserving it",
];

export default phrases;
